# First Pipline
name: Build Windows AMI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

      - name: Install Packer
        uses: hashicorp/setup-packer@v3

      - name: Init Packer
        run: packer init packer/

      - name: Validate Packer
        run: packer validate packer/

      - name: Build AMI
        run: packer build packer/
