name: Build Windows AMI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Packer
        uses: hashicorp/setup-packer@v3

      - name: Verify Packer Version
        run: packer version

      - name: Initialize Packer Plugins
        run: packer init .
        working-directory: ./packer

      - name: Validate Packer Template
        run: packer validate .
        working-directory: ./packer

      - name: Build Windows AMI
        run: packer build .
        working-directory: ./packer
